# Generated by Django 3.1.14 on 2022-11-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=models.CharField(max_length=200)),
        ),
    ]
