# Generated by Django 3.1.14 on 2022-11-12 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_variationmanager_variationvalue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariationManager',
        ),
    ]
