# Generated by Django 3.1.14 on 2022-11-22 23:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_delete_variationmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stok',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)]),
        ),
    ]
