# Generated by Django 3.1.14 on 2022-11-23 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_stok'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipe', to='store.category'),
        ),
    ]
