# Generated by Django 3.1.14 on 2022-11-13 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_auto_20221113_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=15, unique=True, verbose_name='Kupon Diskon'),
        ),
    ]
