# Generated by Django 3.1.14 on 2022-11-13 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_auto_20221113_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': 'Kode Kupon'},
        ),
    ]
