# Generated by Django 3.1.14 on 2022-11-13 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Billingaddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('address1', models.TextField(max_length=100, verbose_name='Alamat')),
                ('address2', models.TextField(verbose_name='Alamat')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kota')),
                ('zipcode', models.CharField(blank=True, max_length=15, null=True, verbose_name='Kode pos')),
                ('phone_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='Nomor Telepon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
