# Generated by Django 3.1.14 on 2022-11-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='address2',
            field=models.TextField(verbose_name='Rincian Alamat'),
        ),
    ]
