# Generated by Django 3.1.14 on 2022-11-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='jenis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
