# Generated by Django 3.1.14 on 2022-11-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_cart_jenis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='jenis',
            field=models.CharField(default='Tidak ada', max_length=100),
        ),
    ]
