# Generated by Django 3.1.14 on 2022-11-13 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20221112_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='jenis',
            field=models.CharField(blank=True, default='Tidak ada', max_length=100, null=True),
        ),
    ]
