# Generated by Django 3.1.14 on 2022-11-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20221113_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash on delivery', 'Cash on Delivery'), ('Dana "fake payment" ', 'Dana "fake payment" ')], default='Cash on delivery', max_length=30),
        ),
    ]
