# Generated by Django 3.1.14 on 2022-11-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash on delivery', 'Cash on Delivery'), ('Dana "fake payment" ', 'Dana "fake payment" ')], default='Cash on delivery', max_length=30, verbose_name='Metode pembayaran'),
        ),
    ]
