# Generated by Django 3.1.14 on 2022-11-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20221124_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
