# Generated by Django 3.1.14 on 2022-11-25 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='catatan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='catatan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pesanan sedang diajukan'), (2, 'Pesanan sedang dikemas'), (3, 'Pesanan sedang diantar'), (4, 'Pesanan sudah sampai'), (5, 'Pesanan telah diambil')], default='1'),
        ),
    ]
